version: '3'
services:
  php-apache:
    build:
        context: ./
    container_name: feedback
    environment:
        TZ: "Europe/Moscow"
    ports:
        - "127.0.0.1:3000:80"
    networks:
        - net
    volumes:
        - ./:/var/www/html
  db:
    image: mariadb:10.1
    container_name: feedback__db
    volumes:
        - ./data/:/var/lib/mysql
    environment:
        TZ: "Europe/Moscow"
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_DATABASE: 'feedback_db'
        MYSQL_USER: 'feedback_db'
        MYSQL_PASSWORD: 'feedback_pass'
    networks:
        - net

networks:
  net:
    driver: bridge
    ipam:
      config:
          - subnet: 172.101.18.20/24
    driver_opts:
          com.docker.network.bridge.name: br-feedback